apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argojk76
  description: Python app that displays time - named argojk76
  annotations:
    github.com/project-slug: jk7testorg/argojk76
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: jk7test/argojk76/main
    argocd/app-name: argojk76
    # argocd/app-selector: app.kubernetes.io/instance=argojk76
    argocd/instance-name: default

spec:
  type: service
  owner: development

  lifecycle: experimental
